version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: notion-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: notion_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - notion-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: notion-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/notion_db
      NOTION_APP_JWT_SECRET: MjE2NzVld3N1eWlvYWFoZGkyMzFnNzgzb2lkd2Fram9kZHdhb2l1cHcxZ2Roby0yOTd1
      NOTION_APP_JWT_EXPIRATION_MS: 86400000
    depends_on:
      - mongodb
    networks:
      - notion-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: notion-frontend
    restart: unless-stopped
    ports:
      - "4200:4200"
    environment:
      - API_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - notion-network

volumes:
  mongodb_data:

networks:
  notion-network:
    driver: bridge 